hydra:
  run:
    dir: results/${hydra.job.name}/${model.name}/${data.type}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project: tuh_CAMS

model:
  name: efficientnet-b2
  classes: 2
  pytorch_implementation: True



data:
  type: train
  data_augmentations: False
  plane: axial
  datasets: [ 'TUH_kidney']
  artifical_spheres: False
  crop_size: 330

check: False



