hydra:
  run:
    dir: results/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project: MIL_TUH_EXP

training:
  epochs: 75
  learning_rate: 1e-4
  weight_decay: 5e-4
  seed: 1


model:
  classes: 2
  name: efficientnet-b2
  pretrained_medicalnet: False

data:
  data_augmentations: False
  plane: axial
  datasets: ['TUH_kidney','totalsegmentor','kits23']
  artifical_spheres: False
  crop_size: 512
  downsample: True
check: False
